# Generated by Django 6.1 on 2026-08-27 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_alerts', models.BooleanField(default=True)),
                ('report_updates', models.BooleanField(default=True)),
                ('system_notifications', models.BooleanField(default=True)),
                ('theme', models.CharField(default='dark', max_length=20)),
                ('language', models.CharField(default='English', max_length=20)),
                ('default_map_view', models.CharField(default='standard', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
