# Generated by Django 6.1 on 2026-08-30 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_reportcomment_reportconfirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='updated_at',
        ),
    ]
